### ISSUE TITLE
problem testing locally: "Page Not Found" and hyperlinks go to the github server instead of the local version

### ISSUE THREAD

**Issue by chcorbato** [kas-lab/kas-lab.github.io#7]
Trying to review Pull request #6 locally the behavior of the website is that hyperlinks refer to the github server, see screenshot:
![Screen Shot 2022-10-20 at 15 17 56](https://user-images.githubusercontent.com/9592617/196959312-bdc7baeb-85f6-4a80-8d4b-818fcd38af67.png)

I explored this error as a potential cause:
`GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.`
I think I solved that error following part of these instructions: https://idratherbewriting.com/documentation-theme-jekyll/mydoc_install_jekyll_on_mac.html#githuberror
Concretely, I added the token to my .bashrc (I could not do the other part with a file) 
However, the issue persists.

have you tested locally @EGAlberts ? How do you do it?

**Comment by EGAlberts** [comment]
If I remember correctly, for some reason during development the hyperlinks go to the live website, therefore as the software page does not exist, it will give you a page not found. However, if you manually type in /software after the localhost:4000 URL, you will get the page I developed. Seeing as accepting the pull request would cause a kaslab/software page to exist, I figured while live the error resolves itself as the hyperlink now goes to an existing page

**Comment by chcorbato** [comment]
> However, if you manually type in /software after the localhost:4000 URL, you will get the page I developed.

Somehow this was not working for me either. I just tested by switching the settings in the repo to use the software branch and then merged your Pull request.

I keep this issue open because it would be helpful if someone figures out how to properly test our website updates.

**Comment by Rezenders** [comment]
To test locally you should run the webpage with this command:

```
bundle exec jekyll serve
```

Instead of:

```
bundle exec jekyll liveserve
```

with this, the base url becomes `localhost:4000`

**Comment by chcorbato** [comment]
Wonderful! Thank you @Rezenders , I have committed the fix of the README [6b4802b](https://github.com/kas-lab/kas-lab.github.io/commit/6b4802b0d87daf9048256690a1531c04c6d64a31)
